#!/usr/bin/python3

import sys
import os

def report_error(filepath, lineno, line, message):
    print(
        f"[ERROR] {filepath}:{lineno}\n"
        f"        {message}\n"
        f"        Offending line: {line!r}\n",
        file=sys.stderr
    )

def main(argv):
    if len(argv) < 2:
        sys.exit(f"Usage: {argv[0]} SYM")

    sym_path = argv[1]

    print(f"\n@ Auto generated by {argv[0]}")

    try:
        with open(sym_path, "r", encoding="utf-8", errors="strict") as f:
            for lineno, line in enumerate(f, start=1):
                try:
                    # Strip newline but keep original for reporting
                    raw_line = line.rstrip("\n")

                    if len(raw_line) < 9:
                        raise ValueError("Line too short to contain address and symbol")

                    addr_str = raw_line[0:8]
                    name = raw_line[9:]

                    # Validate hex address
                    try:
                        addr = int(addr_str, 16)
                    except ValueError:
                        raise ValueError(f"Invalid hex address: '{addr_str}'")

                    ptr = f"0x{addr_str}"

                    if addr & 1:
                        print(f"fun {ptr}, {name}")
                    else:
                        print(f"dat {ptr}, {name}")

                except Exception as e:
                    report_error(sym_path, lineno, line, str(e))

    except UnicodeDecodeError as e:
        print(
            f"[ERROR] {sym_path}\n"
            f"        Unicode decode error: {e}\n"
            f"        Offending bytes around position {e.start}-{e.end}\n",
            file=sys.stderr
        )
        sys.exit(1)

    except OSError as e:
        sys.exit(f"[ERROR] Cannot open file '{sym_path}': {e}")

    print("")

if __name__ == "__main__":
    main(sys.argv)
