#ifndef EVENT_COMMANDS_INSTALLED
#define EVENT_COMMANDS_INSTALLED

#define EVENT_CMD_SKILL 0x46
#define EVENT_CMD_DEBUFF 0x47
#define EVENT_CMD_SCREEN_GLITCH 0x48

#endif /* EVENT_COMMANDS_INSTALLED */
