#define ITEM_ICON_MAG_BOOSTER 0xCA
#define ITEM_ICON_STAR 0xCB
#define ITEM_ICON_SKILL_STEALER 0xCC
#define ITEM_ICON_ARMS_SCROLL 0xCD

#define ITEM_ICON_STAFF_FORCE 0xCE
#define ITEM_ICON_STAFF_ACUITY 0xCF
#define ITEM_ICON_STAFF_FORTUNE 0xDE
#define ITEM_ICON_STAFF_IRON 0xDF
#define ITEM_ICON_STAFF_SPRINT 0xAD
#define ITEM_ICON_STAFF_TEMPEST 0xAE
#define ITEM_ICON_STAFF_OMNI 0x9F

#define ITEM_ICON_STAFF_RUNE 0xAF
#define ITEM_ICON_STAFF_MINE 0x6F
#define ITEM_ICON_STAFF_SLOW 0x78
#define ITEM_ICON_STAFF_FORGE 0xAB
#define ITEM_ICON_STAFF_REWARP 0xAC
#define ITEM_ICON_STAFF_POISON 0xA0
#define ITEM_ICON_STAFF_DELAY 0xA1
#define ITEM_ICON_STAFF_ENTRAP 0xA2
#define ITEM_ICON_STAFF_QUICKEN 0xA3
#define ITEM_ICON_STAFF_HIDE 0xA4
#define ITEM_ICON_STAFF_PROVOKE 0xA5
#define ITEM_ICON_STAFF_PETRIFY 0xA6
#define ITEM_ICON_STAFF_SOOTH 0x97
#define ITEM_ICON_STAFF_ENFEEBLE 0xA7
#define ITEM_ICON_STAFF_INVEST 0xA8