#!/bin/bash
set -euo pipefail

SOURCE_DIR=Sources
INSTALLER=$2
HEADER=$1

rm -f "$INSTALLER" "$HEADER"

SCR_NAME=$(basename "$0")
DAY_TIME=$(date "+%Y-%m-%d %H:%M:%S")

printf '// Auto generated by %s at %s\n\n' "$SCR_NAME" "$DAY_TIME" > "$INSTALLER"
printf '// Auto generated by %s at %s\n\n' "$SCR_NAME" "$DAY_TIME" > "$HEADER"

printf '#ifndef GFX_CONFIG_INSTALLED\n#define GFX_CONFIG_INSTALLED\n\n' >> "$HEADER"

all_sources=$(find "$SOURCE_DIR" -type f -name "*.png")

for file in $all_sources; do
    base_name=$(echo "${file#*/}" | sed 's/\.png//; s/\//_/g')
    target=$(echo "$file" | sed 's/\.png/\.4bpp/')
    printf 'ALIGN 4\nGFX_%s:\n\t#incbin "%s"\n\n' "$base_name" "$target" >> "$INSTALLER"
    printf 'extern const unsigned char GFX_%s[];\n' "$base_name" >> "$HEADER"
done

printf '\n#endif /* GFX_CONFIG_INSTALLED */\n' >> "$HEADER"
