#include "common-chax.h"
#include "jester_headers/custom-arrays.h"
#include "../../../../Contents/Texts/build/msgs.h"

const struct SupportTalkEnt gNewSupportTalkList[] = 
{
    { CHARACTER_EIRIKA, CHARACTER_EPHRAIM, {C_Eirika_Ephraim, B_Eirika_Ephraim, A_Eirika_Ephraim}, 0, 0, 0, 0 },
    { CHARACTER_EIRIKA, CHARACTER_SETH, {C_Eirika_Seth, B_Eirika_Seth, A_Eirika_Seth}, 0, 0, 0, 0 },
    { CHARACTER_EIRIKA, CHARACTER_SALEH, {C_Eirika_Saleh, B_Eirika_Saleh, A_Eirika_Saleh}, 0, 0, 0, 0 },
    { CHARACTER_EIRIKA, CHARACTER_LARACHEL, {C_Eirika_Larachel, B_Eirika_Larachel, A_Eirika_Larachel}, 0, 0, 0, 0 },
    { CHARACTER_EIRIKA, CHARACTER_TANA, {C_Eirika_Tana, B_Eirika_Tana, A_Eirika_Tana}, 0, 0, 0, 0 },
    { CHARACTER_EIRIKA, CHARACTER_INNES, {C_Eirika_Innes, B_Eirika_Innes, A_Eirika_Innes}, 0, 0, 0, 0 },
    { CHARACTER_EIRIKA, CHARACTER_FORDE, {C_Eirika_Forde, B_Eirika_Forde, A_Eirika_Forde}, 0, 0, 0, 0 },

    { CHARACTER_SETH, CHARACTER_FRANZ, {C_Seth_Franz, B_Seth_Franz, A_Seth_Franz}, 0, 0, 0, 0 },
    { CHARACTER_SETH, CHARACTER_EIRIKA, {C_Eirika_Seth, B_Eirika_Seth, A_Eirika_Seth}, 0, 0, 0, 0 },
    { CHARACTER_SETH, CHARACTER_GARCIA, {C_Seth_Garcia, B_Seth_Garcia, A_Seth_Garcia}, 0, 0, 0, 0 },
    { CHARACTER_SETH, CHARACTER_NATASHA, {C_Seth_Natasha, B_Seth_Natasha, A_Seth_Natasha}, 0, 0, 0, 0 },
    { CHARACTER_SETH, CHARACTER_CORMAG, {C_Seth_Cormag, B_Seth_Cormag, A_Seth_Cormag}, 0, 0, 0, 0 },
    { CHARACTER_SETH, CHARACTER_DUESSEL, {C_Seth_Duessel, B_Seth_Duessel, A_Seth_Duessel}, 0, 0, 0, 0 },

    { CHARACTER_GILLIAM, CHARACTER_GARCIA, {C_Gilliam_Garcia, B_Gilliam_Garcia, A_Gilliam_Garcia}, 0, 0, 0, 0 },
    { CHARACTER_GILLIAM, CHARACTER_FRANZ, {C_Gilliam_Franz, B_Gilliam_Franz, A_Gilliam_Franz}, 0, 0, 0, 0 },
    { CHARACTER_GILLIAM, CHARACTER_SYRENE, {C_Gilliam_Syrene, B_Gilliam_Syrene, A_Gilliam_Syrene}, 0, 0, 0, 0 },
    { CHARACTER_GILLIAM, CHARACTER_MOULDER, {C_Gilliam_Moulder, B_Gilliam_Moulder, A_Gilliam_Moulder}, 0, 0, 0, 0 },
    { CHARACTER_GILLIAM, CHARACTER_NEIMI, {C_Gilliam_Neimi, B_Gilliam_Neimi, A_Gilliam_Neimi}, 0, 0, 0, 0 },

    { CHARACTER_FRANZ, CHARACTER_SETH, {C_Seth_Franz, B_Seth_Franz, A_Seth_Franz}, 0, 0, 0, 0 },
    { CHARACTER_FRANZ, CHARACTER_GILLIAM, {C_Gilliam_Franz, B_Gilliam_Franz, A_Gilliam_Franz}, 0, 0, 0, 0 },
    { CHARACTER_FRANZ, CHARACTER_FORDE, {C_Franz_Forde, B_Franz_Forde, A_Franz_Forde}, 0, 0, 0, 0 },
    { CHARACTER_FRANZ, CHARACTER_AMELIA, {C_Franz_Amelia, B_Franz_Amelia, A_Franz_Amelia}, 0, 0, 0, 0 },
    { CHARACTER_FRANZ, CHARACTER_NATASHA, {C_Franz_Natasha, B_Franz_Natasha, A_Franz_Natasha}, 0, 0, 0, 0 },

    { CHARACTER_MOULDER, CHARACTER_VANESSA, {C_Moulder_Vanessa, B_Moulder_Vanessa, A_Moulder_Vanessa}, 0, 0, 0, 0 },
    { CHARACTER_MOULDER, CHARACTER_COLM, {C_Moulder_Colm, B_Moulder_Colm, A_Moulder_Colm}, 0, 0, 0, 0 },
    { CHARACTER_MOULDER, CHARACTER_GILLIAM, {C_Gilliam_Moulder, B_Gilliam_Moulder, A_Gilliam_Moulder}, 0, 0, 0, 0 },
    { CHARACTER_MOULDER, CHARACTER_SYRENE, {C_Moulder_Syrene, B_Moulder_Syrene, A_Moulder_Syrene}, 0, 0, 0, 0 },

    { CHARACTER_VANESSA, CHARACTER_MOULDER, {C_Moulder_Vanessa, B_Moulder_Vanessa, A_Moulder_Vanessa}, 0, 0, 0, 0 },
    { CHARACTER_VANESSA, CHARACTER_SYRENE, {C_Vanessa_Syrene, B_Vanessa_Syrene, A_Vanessa_Syrene}, 0, 0, 0, 0 },
    { CHARACTER_VANESSA, CHARACTER_LUTE, {C_Vanessa_Lute, B_Vanessa_Lute, A_Vanessa_Lute}, 0, 0, 0, 0 },
    { CHARACTER_VANESSA, CHARACTER_FORDE, {C_Vanessa_Forde, B_Vanessa_Forde, A_Vanessa_Forde}, 0, 0, 0, 0 },
    { CHARACTER_VANESSA, CHARACTER_INNES, {C_Vanessa_Innes, B_Vanessa_Innes, A_Vanessa_Innes}, 0, 0, 0, 0 },

    { CHARACTER_ROSS, CHARACTER_GARCIA, {C_Ross_Garcia, B_Ross_Garcia, A_Ross_Garcia}, 0, 0, 0, 0 },
    { CHARACTER_ROSS, CHARACTER_LUTE, {C_Ross_Lute, B_Ross_Lute, A_Ross_Lute}, 0, 0, 0, 0 },
    { CHARACTER_ROSS, CHARACTER_AMELIA, {C_Ross_Amelia, B_Ross_Amelia, A_Ross_Amelia}, 0, 0, 0, 0 },
    { CHARACTER_ROSS, CHARACTER_EWAN, {C_Ross_Ewan, B_Ross_Ewan, A_Ross_Ewan}, 0, 0, 0, 0 },
    { CHARACTER_ROSS, CHARACTER_GERIK, {C_Ross_Gerik, B_Ross_Gerik, A_Ross_Gerik}, 0, 0, 0, 0 },

    { CHARACTER_NEIMI, CHARACTER_COLM, {C_Neimi_Colm, B_Neimi_Colm, A_Neimi_Colm}, 0, 0, 0, 0 },
    { CHARACTER_NEIMI, CHARACTER_GARCIA, {C_Neimi_Garcia, B_Neimi_Garcia, A_Neimi_Garcia}, 0, 0, 0, 0 },
    { CHARACTER_NEIMI, CHARACTER_AMELIA, {C_Neimi_Amelia, B_Neimi_Amelia, A_Neimi_Amelia}, 0, 0, 0, 0 },
    { CHARACTER_NEIMI, CHARACTER_ARTUR, {C_Neimi_Artur, B_Neimi_Artur, A_Neimi_Artur}, 0, 0, 0, 0 },
    { CHARACTER_NEIMI, CHARACTER_GILLIAM, {C_Gilliam_Neimi, B_Gilliam_Neimi, A_Gilliam_Neimi}, 0, 0, 0, 0 },

    { CHARACTER_COLM, CHARACTER_NEIMI, {C_Neimi_Colm, B_Neimi_Colm, A_Neimi_Colm}, 0, 0, 0, 0 },
    { CHARACTER_COLM, CHARACTER_MARISA, {C_Colm_Marisa, B_Colm_Marisa, A_Colm_Marisa}, 0, 0, 0, 0 },
    { CHARACTER_COLM, CHARACTER_RENNAC, {C_Colm_Rennac, B_Colm_Rennac, A_Colm_Rennac}, 0, 0, 0, 0 },
    { CHARACTER_COLM, CHARACTER_MOULDER, {C_Moulder_Colm, B_Moulder_Colm, A_Moulder_Colm}, 0, 0, 0, 0 },
    { CHARACTER_COLM, CHARACTER_KYLE, {C_Colm_Kyle, B_Colm_Kyle, A_Colm_Kyle}, 0, 0, 0, 0 },

    { CHARACTER_GARCIA, CHARACTER_ROSS, {C_Ross_Garcia, B_Ross_Garcia, A_Ross_Garcia}, 0, 0, 0, 0 },
    { CHARACTER_GARCIA, CHARACTER_DOZLA, {C_Garcia_Dozla, B_Garcia_Dozla, A_Garcia_Dozla}, 0, 0, 0, 0 },
    { CHARACTER_GARCIA, CHARACTER_SETH, {C_Seth_Garcia, B_Seth_Garcia, A_Seth_Garcia}, 0, 0, 0, 0 },
    { CHARACTER_GARCIA, CHARACTER_NEIMI, {C_Neimi_Garcia, B_Neimi_Garcia, A_Neimi_Garcia}, 0, 0, 0, 0 },
    { CHARACTER_GARCIA, CHARACTER_GILLIAM, {C_Gilliam_Garcia, B_Gilliam_Garcia, A_Gilliam_Garcia}, 0, 0, 0, 0 },

    { CHARACTER_INNES, CHARACTER_GERIK, {C_Innes_Gerik, B_Innes_Gerik, A_Innes_Gerik}, 0, 0, 0, 0 },
    { CHARACTER_INNES, CHARACTER_VANESSA, {C_Vanessa_Innes, B_Vanessa_Innes, A_Vanessa_Innes}, 0, 0, 0, 0 },
    { CHARACTER_INNES, CHARACTER_TANA, {C_Innes_Tana, B_Innes_Tana, A_Innes_Tana}, 0, 0, 0, 0 },
    { CHARACTER_INNES, CHARACTER_JOSHUA, {C_Innes_Joshua, B_Innes_Joshua, A_Innes_Joshua}, 0, 0, 0, 0 },
    { CHARACTER_INNES, CHARACTER_LARACHEL, {C_Innes_Larachel, B_Innes_Larachel, A_Innes_Larachel}, 0, 0, 0, 0 },
    { CHARACTER_INNES, CHARACTER_EIRIKA, {C_Eirika_Innes, B_Eirika_Innes, A_Eirika_Innes}, 0, 0, 0, 0 },

    { CHARACTER_LUTE, CHARACTER_ARTUR, {C_Lute_Artur, B_Lute_Artur, A_Lute_Artur}, 0, 0, 0, 0 },
    { CHARACTER_LUTE, CHARACTER_ROSS, {C_Ross_Lute, B_Ross_Lute, A_Ross_Lute}, 0, 0, 0, 0 },
    { CHARACTER_LUTE, CHARACTER_KNOLL, {C_Lute_Knoll, B_Lute_Knoll, A_Lute_Knoll}, 0, 0, 0, 0 },
    { CHARACTER_LUTE, CHARACTER_KYLE, {C_Lute_Kyle, B_Lute_Kyle, A_Lute_Kyle}, 0, 0, 0, 0 },
    { CHARACTER_LUTE, CHARACTER_VANESSA, {C_Vanessa_Lute, B_Vanessa_Lute, A_Vanessa_Lute}, 0, 0, 0, 0 },

    { CHARACTER_NATASHA, CHARACTER_JOSHUA, {C_Natasha_Joshua, B_Natasha_Joshua, A_Natasha_Joshua}, 0, 0, 0, 0 },
    { CHARACTER_NATASHA, CHARACTER_KNOLL, {C_Natasha_Knoll, B_Natasha_Knoll, A_Natasha_Knoll}, 0, 0, 0, 0 },
    { CHARACTER_NATASHA, CHARACTER_CORMAG, {C_Natasha_Cormag, B_Natasha_Cormag, A_Natasha_Cormag}, 0, 0, 0, 0 },
    { CHARACTER_NATASHA, CHARACTER_SETH, {C_Seth_Natasha, B_Seth_Natasha, A_Seth_Natasha}, 0, 0, 0, 0 },
    { CHARACTER_NATASHA, CHARACTER_FRANZ, {C_Franz_Natasha, B_Franz_Natasha, A_Franz_Natasha}, 0, 0, 0, 0 },

    { CHARACTER_CORMAG, CHARACTER_DUESSEL, {C_Cormag_Duessel, B_Cormag_Duessel, A_Cormag_Duessel}, 0, 0, 0, 0 },
    { CHARACTER_CORMAG, CHARACTER_TANA, {C_Cormag_Tana, B_Cormag_Tana, A_Cormag_Tana}, 0, 0, 0, 0 },
    { CHARACTER_CORMAG, CHARACTER_NATASHA, {C_Natasha_Cormag, B_Natasha_Cormag, A_Natasha_Cormag}, 0, 0, 0, 0 },
    { CHARACTER_CORMAG, CHARACTER_ARTUR, {C_Cormag_Artur, B_Cormag_Artur, A_Cormag_Artur}, 0, 0, 0, 0 },
    { CHARACTER_CORMAG, CHARACTER_SETH, {C_Seth_Cormag, B_Seth_Cormag, A_Seth_Cormag}, 0, 0, 0, 0 },

    { CHARACTER_EPHRAIM, CHARACTER_EIRIKA, {C_Eirika_Ephraim, B_Eirika_Ephraim, A_Eirika_Ephraim}, 0, 0, 0, 0 },
    { CHARACTER_EPHRAIM, CHARACTER_KYLE, {C_Ephraim_Kyle, B_Ephraim_Kyle, A_Ephraim_Kyle}, 0, 0, 0, 0 },
    { CHARACTER_EPHRAIM, CHARACTER_FORDE, {C_Ephraim_Forde, B_Ephraim_Forde, A_Ephraim_Forde}, 0, 0, 0, 0 },
    { CHARACTER_EPHRAIM, CHARACTER_MYRRH, {C_Ephraim_Myrrh, B_Ephraim_Myrrh, A_Ephraim_Myrrh}, 0, 0, 0, 0 },
    { CHARACTER_EPHRAIM, CHARACTER_LARACHEL, {C_Ephraim_Larachel, B_Ephraim_Larachel, A_Ephraim_Larachel}, 0, 0, 0, 0 },
    { CHARACTER_EPHRAIM, CHARACTER_DUESSEL, {C_Ephraim_Duessel, B_Ephraim_Duessel, A_Ephraim_Duessel}, 0, 0, 0, 0 },
    { CHARACTER_EPHRAIM, CHARACTER_TANA, {C_Ephraim_Tana, B_Ephraim_Tana, A_Ephraim_Tana}, 0, 0, 0, 0 },

    { CHARACTER_FORDE, CHARACTER_KYLE, {C_Forde_Kyle, B_Forde_Kyle, A_Forde_Kyle}, 0, 0, 0, 0 },
    { CHARACTER_FORDE, CHARACTER_VANESSA, {C_Vanessa_Forde, B_Vanessa_Forde, A_Vanessa_Forde}, 0, 0, 0, 0 },
    { CHARACTER_FORDE, CHARACTER_EPHRAIM, {C_Ephraim_Forde, B_Ephraim_Forde, A_Ephraim_Forde}, 0, 0, 0, 0 },
    { CHARACTER_FORDE, CHARACTER_FRANZ, {C_Franz_Forde, B_Franz_Forde, A_Franz_Forde}, 0, 0, 0, 0 },
    { CHARACTER_FORDE, CHARACTER_EIRIKA, {C_Eirika_Forde, B_Eirika_Forde, A_Eirika_Forde}, 0, 0, 0, 0 },

    { CHARACTER_KYLE, CHARACTER_FORDE, {C_Forde_Kyle, B_Forde_Kyle, A_Forde_Kyle}, 0, 0, 0, 0 },
    { CHARACTER_KYLE, CHARACTER_EPHRAIM, {C_Ephraim_Kyle, B_Ephraim_Kyle, A_Ephraim_Kyle}, 0, 0, 0, 0 },
    { CHARACTER_KYLE, CHARACTER_SYRENE, {C_Kyle_Syrene, B_Kyle_Syrene, A_Kyle_Syrene}, 0, 0, 0, 0 },
    { CHARACTER_KYLE, CHARACTER_COLM, {C_Colm_Kyle, B_Colm_Kyle, A_Colm_Kyle}, 0, 0, 0, 0 },
    { CHARACTER_KYLE, CHARACTER_LUTE, {C_Lute_Kyle, B_Lute_Kyle, A_Lute_Kyle}, 0, 0, 0, 0 },

    { CHARACTER_AMELIA, CHARACTER_NEIMI, {C_Neimi_Amelia, B_Neimi_Amelia, A_Neimi_Amelia}, 0, 0, 0, 0 },
    { CHARACTER_AMELIA, CHARACTER_DUESSEL, {C_Amelia_Duessel, B_Amelia_Duessel, A_Amelia_Duessel}, 0, 0, 0, 0 },
    { CHARACTER_AMELIA, CHARACTER_EWAN, {C_Amelia_Ewan, B_Amelia_Ewan, A_Amelia_Ewan}, 0, 0, 0, 0 },
    { CHARACTER_AMELIA, CHARACTER_ROSS, {C_Ross_Amelia, B_Ross_Amelia, A_Ross_Amelia}, 0, 0, 0, 0 },
    { CHARACTER_AMELIA, CHARACTER_FRANZ, {C_Franz_Amelia, B_Franz_Amelia, A_Franz_Amelia}, 0, 0, 0, 0 },

    { CHARACTER_ARTUR, CHARACTER_LUTE, {C_Lute_Artur, B_Lute_Artur, A_Lute_Artur}, 0, 0, 0, 0 },
    { CHARACTER_ARTUR, CHARACTER_TETHYS, {C_Artur_Tethys, B_Artur_Tethys, A_Artur_Tethys}, 0, 0, 0, 0 },
    { CHARACTER_ARTUR, CHARACTER_CORMAG, {C_Cormag_Artur, B_Cormag_Artur, A_Cormag_Artur}, 0, 0, 0, 0 },
    { CHARACTER_ARTUR, CHARACTER_NEIMI, {C_Neimi_Artur, B_Neimi_Artur, A_Neimi_Artur}, 0, 0, 0, 0 },
    { CHARACTER_ARTUR, CHARACTER_JOSHUA, {C_Artur_Joshua, B_Artur_Joshua, A_Artur_Joshua}, 0, 0, 0, 0 },

    { CHARACTER_GERIK, CHARACTER_INNES, {C_Innes_Gerik, B_Innes_Gerik, A_Innes_Gerik}, 0, 0, 0, 0 },
    { CHARACTER_GERIK, CHARACTER_TETHYS, {C_Gerik_Tethys, B_Gerik_Tethys, A_Gerik_Tethys}, 0, 0, 0, 0 },
    { CHARACTER_GERIK, CHARACTER_MARISA, {C_Gerik_Marisa, B_Gerik_Marisa, A_Gerik_Marisa}, 0, 0, 0, 0 },
    { CHARACTER_GERIK, CHARACTER_SALEH, {C_Gerik_Saleh, B_Gerik_Saleh, A_Gerik_Saleh}, 0, 0, 0, 0 },
    { CHARACTER_GERIK, CHARACTER_JOSHUA, {C_Gerik_Joshua, B_Gerik_Joshua, A_Gerik_Joshua}, 0, 0, 0, 0 },
    { CHARACTER_GERIK, CHARACTER_ROSS, {C_Ross_Gerik, B_Ross_Gerik, A_Ross_Gerik}, 0, 0, 0, 0 },

    { CHARACTER_TETHYS, CHARACTER_EWAN, {C_Tethys_Ewan, B_Tethys_Ewan, A_Tethys_Ewan}, 0, 0, 0, 0 },
    { CHARACTER_TETHYS, CHARACTER_GERIK, {C_Gerik_Tethys, B_Gerik_Tethys, A_Gerik_Tethys}, 0, 0, 0, 0 },
    { CHARACTER_TETHYS, CHARACTER_MARISA, {C_Tethys_Marisa, B_Tethys_Marisa, A_Tethys_Marisa}, 0, 0, 0, 0 },
    { CHARACTER_TETHYS, CHARACTER_RENNAC, {C_Tethys_Rennac, B_Tethys_Rennac, A_Tethys_Rennac}, 0, 0, 0, 0 },
    { CHARACTER_TETHYS, CHARACTER_ARTUR, {C_Artur_Tethys, B_Artur_Tethys, A_Artur_Tethys}, 0, 0, 0, 0 },

    { CHARACTER_MARISA, CHARACTER_TANA, {C_Marisa_Tana, B_Marisa_Tana, A_Marisa_Tana}, 0, 0, 0, 0 },
    { CHARACTER_MARISA, CHARACTER_TETHYS, {C_Tethys_Marisa, B_Tethys_Marisa, A_Tethys_Marisa}, 0, 0, 0, 0 },
    { CHARACTER_MARISA, CHARACTER_GERIK, {C_Gerik_Marisa, B_Gerik_Marisa, A_Gerik_Marisa}, 0, 0, 0, 0 },
    { CHARACTER_MARISA, CHARACTER_COLM, {C_Colm_Marisa, B_Colm_Marisa, A_Colm_Marisa}, 0, 0, 0, 0 },
    { CHARACTER_MARISA, CHARACTER_JOSHUA, {C_Marisa_Joshua, B_Marisa_Joshua, A_Marisa_Joshua}, 0, 0, 0, 0 },

    { CHARACTER_SALEH, CHARACTER_MYRRH, {C_Saleh_Myrrh, B_Saleh_Myrrh, A_Saleh_Myrrh}, 0, 0, 0, 0 },
    { CHARACTER_SALEH, CHARACTER_EWAN, {C_Saleh_Ewan, B_Saleh_Ewan, A_Saleh_Ewan}, 0, 0, 0, 0 },
    { CHARACTER_SALEH, CHARACTER_GERIK, {C_Gerik_Saleh, B_Gerik_Saleh, A_Gerik_Saleh}, 0, 0, 0, 0 },
    { CHARACTER_SALEH, CHARACTER_EIRIKA, {C_Eirika_Saleh, B_Eirika_Saleh, A_Eirika_Saleh}, 0, 0, 0, 0 },

    { CHARACTER_EWAN, CHARACTER_TETHYS, {C_Tethys_Ewan, B_Tethys_Ewan, A_Tethys_Ewan}, 0, 0, 0, 0 },
    { CHARACTER_EWAN, CHARACTER_SALEH, {C_Saleh_Ewan, B_Saleh_Ewan, A_Saleh_Ewan}, 0, 0, 0, 0 },
    { CHARACTER_EWAN, CHARACTER_DOZLA, {C_Ewan_Dozla, B_Ewan_Dozla, A_Ewan_Dozla}, 0, 0, 0, 0 },
    { CHARACTER_EWAN, CHARACTER_AMELIA, {C_Amelia_Ewan, B_Amelia_Ewan, A_Amelia_Ewan}, 0, 0, 0, 0 },
    { CHARACTER_EWAN, CHARACTER_ROSS, {C_Ross_Ewan, B_Ross_Ewan, A_Ross_Ewan}, 0, 0, 0, 0 },
    { CHARACTER_EWAN, CHARACTER_MYRRH, {C_Ewan_Myrrh, B_Ewan_Myrrh, A_Ewan_Myrrh}, 0, 0, 0, 0 },

    { CHARACTER_LARACHEL, CHARACTER_DOZLA, {C_Larachel_Dozla, B_Larachel_Dozla, A_Larachel_Dozla}, 0, 0, 0, 0 },
    { CHARACTER_LARACHEL, CHARACTER_RENNAC, {C_Larachel_Rennac, B_Larachel_Rennac, A_Larachel_Rennac}, 0, 0, 0, 0 },
    { CHARACTER_LARACHEL, CHARACTER_JOSHUA, {C_Larachel_Joshua, B_Larachel_Joshua, A_Larachel_Joshua}, 0, 0, 0, 0 },
    { CHARACTER_LARACHEL, CHARACTER_EIRIKA, {C_Eirika_Larachel, B_Eirika_Larachel, A_Eirika_Larachel}, 0, 0, 0, 0 },
    { CHARACTER_LARACHEL, CHARACTER_EPHRAIM, {C_Ephraim_Larachel, B_Ephraim_Larachel, A_Ephraim_Larachel}, 0, 0, 0, 0 },
    { CHARACTER_LARACHEL, CHARACTER_INNES, {C_Innes_Larachel, B_Innes_Larachel, A_Innes_Larachel}, 0, 0, 0, 0 },

    { CHARACTER_DOZLA, CHARACTER_LARACHEL, {C_Larachel_Dozla, B_Larachel_Dozla, A_Larachel_Dozla}, 0, 0, 0, 0 },
    { CHARACTER_DOZLA, CHARACTER_MYRRH, {C_Dozla_Myrrh, B_Dozla_Myrrh, A_Dozla_Myrrh}, 0, 0, 0, 0 },
    { CHARACTER_DOZLA, CHARACTER_RENNAC, {C_Dozla_Rennac, B_Dozla_Rennac, A_Dozla_Rennac}, 0, 0, 0, 0 },
    { CHARACTER_DOZLA, CHARACTER_EWAN, {C_Ewan_Dozla, B_Ewan_Dozla, A_Ewan_Dozla}, 0, 0, 0, 0 },
    { CHARACTER_DOZLA, CHARACTER_GARCIA, {C_Garcia_Dozla, B_Garcia_Dozla, A_Garcia_Dozla}, 0, 0, 0, 0 },

    { CHARACTER_RENNAC, CHARACTER_TETHYS, {C_Tethys_Rennac, B_Tethys_Rennac, A_Tethys_Rennac}, 0, 0, 0, 0 },
    { CHARACTER_RENNAC, CHARACTER_LARACHEL, {C_Larachel_Rennac, B_Larachel_Rennac, A_Larachel_Rennac}, 0, 0, 0, 0 },
    { CHARACTER_RENNAC, CHARACTER_DOZLA, {C_Dozla_Rennac, B_Dozla_Rennac, A_Dozla_Rennac}, 0, 0, 0, 0 },
    { CHARACTER_RENNAC, CHARACTER_COLM, {C_Colm_Rennac, B_Colm_Rennac, A_Colm_Rennac}, 0, 0, 0, 0 },
    { CHARACTER_RENNAC, CHARACTER_JOSHUA, {C_Joshua_Rennac, B_Joshua_Rennac, A_Joshua_Rennac}, 0, 0, 0, 0 },

    { CHARACTER_DUESSEL, CHARACTER_CORMAG, {C_Cormag_Duessel, B_Cormag_Duessel, A_Cormag_Duessel}, 0, 0, 0, 0 },
    { CHARACTER_DUESSEL, CHARACTER_AMELIA, {C_Amelia_Duessel, B_Amelia_Duessel, A_Amelia_Duessel}, 0, 0, 0, 0 },
    { CHARACTER_DUESSEL, CHARACTER_KNOLL, {C_Duessel_Knoll, B_Duessel_Knoll, A_Duessel_Knoll}, 0, 0, 0, 0 },
    { CHARACTER_DUESSEL, CHARACTER_EPHRAIM, {C_Ephraim_Duessel, B_Ephraim_Duessel, A_Ephraim_Duessel}, 0, 0, 0, 0 },
    { CHARACTER_DUESSEL, CHARACTER_SETH, {C_Seth_Duessel, B_Seth_Duessel, A_Seth_Duessel}, 0, 0, 0, 0 },

    { CHARACTER_MYRRH, CHARACTER_SALEH, {C_Saleh_Myrrh, B_Saleh_Myrrh, A_Saleh_Myrrh}, 0, 0, 0, 0 },
    { CHARACTER_MYRRH, CHARACTER_DOZLA, {C_Dozla_Myrrh, B_Dozla_Myrrh, A_Dozla_Myrrh}, 0, 0, 0, 0 },
    { CHARACTER_MYRRH, CHARACTER_EPHRAIM, {C_Ephraim_Myrrh, B_Ephraim_Myrrh, A_Ephraim_Myrrh}, 0, 0, 0, 0 },
    { CHARACTER_MYRRH, CHARACTER_EWAN, {C_Ewan_Myrrh, B_Ewan_Myrrh, A_Ewan_Myrrh}, 0, 0, 0, 0 },

    { CHARACTER_KNOLL, CHARACTER_NATASHA, {C_Natasha_Knoll, B_Natasha_Knoll, A_Natasha_Knoll}, 0, 0, 0, 0 },
    { CHARACTER_KNOLL, CHARACTER_DUESSEL, {C_Duessel_Knoll, B_Duessel_Knoll, A_Duessel_Knoll}, 0, 0, 0, 0 },
    { CHARACTER_KNOLL, CHARACTER_LUTE, {C_Lute_Knoll, B_Lute_Knoll, A_Lute_Knoll}, 0, 0, 0, 0 },

    { CHARACTER_JOSHUA, CHARACTER_NATASHA, {C_Natasha_Joshua, B_Natasha_Joshua, A_Natasha_Joshua}, 0, 0, 0, 0 },
    { CHARACTER_JOSHUA, CHARACTER_INNES, {C_Innes_Joshua, B_Innes_Joshua, A_Innes_Joshua}, 0, 0, 0, 0 },
    { CHARACTER_JOSHUA, CHARACTER_ARTUR, {C_Artur_Joshua, B_Artur_Joshua, A_Artur_Joshua}, 0, 0, 0, 0 },
    { CHARACTER_JOSHUA, CHARACTER_LARACHEL, {C_Larachel_Joshua, B_Larachel_Joshua, A_Larachel_Joshua}, 0, 0, 0, 0 },
    { CHARACTER_JOSHUA, CHARACTER_MARISA, {C_Marisa_Joshua, B_Marisa_Joshua, A_Marisa_Joshua}, 0, 0, 0, 0 },
    { CHARACTER_JOSHUA, CHARACTER_GERIK, {C_Gerik_Joshua, B_Gerik_Joshua, A_Gerik_Joshua}, 0, 0, 0, 0 },
    { CHARACTER_JOSHUA, CHARACTER_RENNAC, {C_Joshua_Rennac, B_Joshua_Rennac, A_Joshua_Rennac}, 0, 0, 0, 0 },

    { CHARACTER_SYRENE, CHARACTER_KYLE, {C_Kyle_Syrene, B_Kyle_Syrene, A_Kyle_Syrene}, 0, 0, 0, 0 },
    { CHARACTER_SYRENE, CHARACTER_VANESSA, {C_Vanessa_Syrene, B_Vanessa_Syrene, A_Vanessa_Syrene}, 0, 0, 0, 0 },
    { CHARACTER_SYRENE, CHARACTER_MOULDER, {C_Moulder_Syrene, B_Moulder_Syrene, A_Moulder_Syrene}, 0, 0, 0, 0 },
    { CHARACTER_SYRENE, CHARACTER_GILLIAM, {C_Gilliam_Syrene, B_Gilliam_Syrene, A_Gilliam_Syrene}, 0, 0, 0, 0 },
    { CHARACTER_SYRENE, CHARACTER_TANA, {C_Syrene_Tana, B_Syrene_Tana, A_Syrene_Tana}, 0, 0, 0, 0 },

    { CHARACTER_TANA, CHARACTER_EPHRAIM, {C_Ephraim_Tana, B_Ephraim_Tana, A_Ephraim_Tana}, 0, 0, 0, 0 },
    { CHARACTER_TANA, CHARACTER_SYRENE, {C_Syrene_Tana, B_Syrene_Tana, A_Syrene_Tana}, 0, 0, 0, 0 },
    { CHARACTER_TANA, CHARACTER_CORMAG, {C_Cormag_Tana, B_Cormag_Tana, A_Cormag_Tana}, 0, 0, 0, 0 },
    { CHARACTER_TANA, CHARACTER_INNES, {C_Innes_Tana, B_Innes_Tana, A_Innes_Tana}, 0, 0, 0, 0 },
    { CHARACTER_TANA, CHARACTER_EIRIKA, {C_Eirika_Tana, B_Eirika_Tana, A_Eirika_Tana}, 0, 0, 0, 0 },
    { CHARACTER_TANA, CHARACTER_MARISA, {C_Marisa_Tana, B_Marisa_Tana, A_Marisa_Tana}, 0, 0, 0, 0 },

    { 0xFFFF,             0x0000,             {0x0000, 0x000, 0x0000}, 0, 0, 0, 0 },
};