// EIRIKA
#define DECLARE_THOUGHT_BUBBLE_GFX(unit, chapter) \
extern u8 Gfx_Chapter_##chapter##_Thought_Bubble_##unit##_Left[]; \
extern u8 Gfx_Chapter_##chapter##_Thought_Bubble_##unit##_Right[]

DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 09);

// SETH
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 09);

#undef DECLARE_THOUGHT_BUBBLE_GFX

typedef struct {
    u8 * const bubble[2];
} WorldMapThoughtBubbleEntryGraphics;
