// EIRIKA
#define DECLARE_THOUGHT_BUBBLE_GFX(unit, chapter) \
extern u8 Gfx_Chapter_##chapter##_Thought_Bubble_##unit##_Left[]; \
extern u8 Gfx_Chapter_##chapter##_Thought_Bubble_##unit##_Right[]

// Eirika
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Eirika, 09);

// Seth
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Seth, 09);

// Franz
DECLARE_THOUGHT_BUBBLE_GFX(Franz, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Franz, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Franz, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Franz, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Franz, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Franz, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Franz, 09);

// Gilliam
DECLARE_THOUGHT_BUBBLE_GFX(Gilliam, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Gilliam, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Gilliam, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Gilliam, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Gilliam, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Gilliam, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Gilliam, 09);

// Moulder
DECLARE_THOUGHT_BUBBLE_GFX(Moulder, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Moulder, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Moulder, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Moulder, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Moulder, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Moulder, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Moulder, 09);

// Tana
DECLARE_THOUGHT_BUBBLE_GFX(Tana, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Tana, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Tana, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Tana, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Tana, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Tana, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Tana, 09);

// Ross
DECLARE_THOUGHT_BUBBLE_GFX(Ross, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Ross, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Ross, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Ross, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Ross, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Ross, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Ross, 09);

// Neimi
DECLARE_THOUGHT_BUBBLE_GFX(Neimi, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Neimi, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Neimi, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Neimi, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Neimi, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Neimi, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Neimi, 09);

// Colm
DECLARE_THOUGHT_BUBBLE_GFX(Colm, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Colm, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Colm, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Colm, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Colm, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Colm, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Colm, 09);

// Garcia
DECLARE_THOUGHT_BUBBLE_GFX(Garcia, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Garcia, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Garcia, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Garcia, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Garcia, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Garcia, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Garcia, 09);

// Artur
DECLARE_THOUGHT_BUBBLE_GFX(Artur, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Artur, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Artur, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Artur, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Artur, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Artur, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Artur, 09);

// Lute
DECLARE_THOUGHT_BUBBLE_GFX(Lute, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Lute, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Lute, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Lute, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Lute, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Lute, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Lute, 09);

// Joshua
DECLARE_THOUGHT_BUBBLE_GFX(Joshua, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Joshua, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Joshua, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Joshua, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Joshua, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Joshua, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Joshua, 09);

// Natasha
DECLARE_THOUGHT_BUBBLE_GFX(Natasha, 02);
DECLARE_THOUGHT_BUBBLE_GFX(Natasha, 03);
DECLARE_THOUGHT_BUBBLE_GFX(Natasha, 04);
DECLARE_THOUGHT_BUBBLE_GFX(Natasha, 05);
DECLARE_THOUGHT_BUBBLE_GFX(Natasha, 06);
DECLARE_THOUGHT_BUBBLE_GFX(Natasha, 07);
DECLARE_THOUGHT_BUBBLE_GFX(Natasha, 09);

#undef DECLARE_THOUGHT_BUBBLE_GFX

typedef struct {
    u8 * const bubble[2];
} WorldMapThoughtBubbleEntryGraphics;
